login: YOUR_LOGIN
password: YOUR_PASSWORD

host: pornolab.net
protocol: http
login_path: /forum/login.php
search_path: /forum/tracker.php

login_field_name: login_username
password_field_name: login_password
